### ISSUE TITLE
AWSTimestamp instead of Int

### ISSUE THREAD

**Issue by avlonder** [flogy/graphql-ttl-transformer#1]
Thanks a lot!
One small remark: Isn't it more appropriate to use the AWSTimestamp scalar type instead of Int?

**Comment by flogy** [comment]
Good point, thank you!

[This article](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-before-you-start.html) states that "The TTL attribute’s value must be a Number data type." and "The TTL attribute’s value must be a timestamp in Unix epoch time format in seconds.". That's why I initially went with `Int`.

However, in the [AWS AppSync Developer Guide](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) I just found this paragraph: "The AWSTimestamp scalar type represents the number of seconds that have elapsed since 1970-01-01T00:00Z. Timestamps are serialized and deserialized as numbers."

So do I understand correctly that `AWSTimestamp` would indeed work for TTL as well, as the serialization and deserialization happens prior to the DynamoDB layer?

**Comment by avlonder** [comment]
Sorry, I'm not an expert.
The only thing I can say is: I changed the Int warning in your module, I compiled my schema with your ttl directive, and it seems to work.

**Comment by flogy** [comment]
Okay, thank you. I have now created a new [1.1.0](https://github.com/flogy/graphql-ttl-transformer/releases/tag/v1.1.0) release that allows both `AWSTimestamp` and `Int` types. The updated README file recommends using `AWSTimestamp` though. `Int` is just still there to not have a breaking change already 🙂👍

Thanks for the issue and enjoy using the library!
